### ISSUE TITLE
Visual Studio discover only one project with tests

### ISSUE THREAD

**Issue by FoggyFinder** [YoloDev/YoloDev.Expecto.TestSdk#10]
Visual Studio discover only one project in case when solution contains more than one project with tests.

Not sure is it really Q for `YoloDev.Expecto.TestSdk`

**Comment by Alxandr** [comment]
Could you provide a minimal reproduction of this?

**Comment by FoggyFinder** [comment]
Sure
https://github.com/FoggyFinder/YoloDevMCVE

**Comment by Alxandr** [comment]
Adding an explicit dependency on `FSharp.Core` in both projects fixes it, but yes I'd say this is a bug, though I'm not entirely sure where. Also, I never expected the project to be used from C#, so it's never been tested. For now, though, you can use a dependency on `FSharp.Core` as a workaround (needs to be added to both projects).

PS: Only tested from the command line on a mac. Don't have VS available. But there was a crash-bug in loading the tests from the C# project which is likely what is causing VS to simply hide the tests.

**Comment by FoggyFinder** [comment]
C# tests project still works perfectly if this project is sole even from VS.

> PS: Only tested from the command line on a mac.

From the command line on win both projects works like a charm

**Comment by Alxandr** [comment]
The issue is that when you have a F# project there is a version conflict for `FSharp.Core`. My guess is that it's related to https://github.com/Microsoft/visualfsharp/issues/3678. @TheAngryByrd you wanted to add `FSharp.Core` explicitly as a dependency to `YoloDev.Expecto.TestSdk`, but I think it might be causing issues. Why was this needed again?

**Comment by Alxandr** [comment]
![image](https://user-images.githubusercontent.com/112334/38323543-d1123d66-383d-11e8-9bc7-8c8a839fdf88.png)

@FoggyFinder it seems to be a VS issue? At least there's a workaround.

**Comment by Alxandr** [comment]
![image](https://user-images.githubusercontent.com/112334/38323614-0a8dee96-383e-11e8-9955-46a754843677.png)

You might need to clean sln before they show up.

**Comment by FoggyFinder** [comment]
Nope, workaround doesn't work for me.

![tests](https://user-images.githubusercontent.com/16510738/38324195-3b6561a2-3848-11e8-9f1e-f774ba9dc00e.jpg)

From log (Even with check "Additionally..") I see that VS found both project but one wasn't run without any messages:

> [04.04.2018 20:23:05 Informational] ------ Начато обнаружение тестов ------
[04.04.2018 20:23:21 Informational] ========== Обнаружение тестов завершено. Найдено: 1
[04.04.2018 20:23:21 Informational] ------ Начато выполнение тестов ------
[04.04.2018 20:23:24 Informational] ========== Выполнение тестов завершено. Выполнено: 1
[04.04.2018 20:23:24 Informational] ------ Начато обнаружение тестов ------
[04.04.2018 20:23:26 Informational] ========== Обнаружение тестов завершено. Найдено: 1 

(Sorry for language my VS with localization)

Without check I got exception

> System.IO.FileNotFoundException: There is no available tests

But if I unload F# project there is no exception and test just runs:

![tests2](https://user-images.githubusercontent.com/16510738/38324194-3b3831d2-3848-11e8-8bdc-97d7b6fd27bb.jpg)

**Comment by FoggyFinder** [comment]
I can't reproduce this on VS2017, so I'll close this.
