### ISSUE TITLE
How to log to the console?

### ISSUE THREAD

**Issue by MangelMaxime** [YoloDev/YoloDev.Expecto.TestSdk#106]
Hello,

when debugging my code I am using printing the console however running `dotnet test` doens't print anything to the console.

```fs
    [<Tests>]
    let tests =
        testList "Capabilities.Auth" [

            test "Database" {
                printfn "Hello from maxime"
                System.Console.WriteLine ("hiduzhdz")
                Expect.equal true true ""
            }

        ]
```

I am using :

```fs
module Antidote.Server.Tests.Program

open Expecto

[<EntryPoint>]
let main argv =
    runTestsInAssembly defaultConfig argv
```

I tried to run using `dotnet test --logger:"console;verbosity=detailed"` without success.

One way to have the log in the console is to make the program an executable and use `dotnet run` instead.

**Comment by Alxandr** [comment]
This is due to how dotnet test works, and has nothing to do with this library. The tests are run in separate processes, and stdout/stderr is collected. You should look into how to log from dotnet test in general. Also, I beehive the test explorer in visual studio/rider will show the console output.

**Comment by MangelMaxime** [comment]
It indeed seems like with Rider, there is a way using 2-3 clicks to access the output of the tests. Thanks for the info

It is a shame that `dotnet test` make it this complicated to have logs...

**Comment by Alxandr** [comment]
It's generally for good reason. Especially when you have a couple of failing tests, it's very useful to easily see which tests produced which output (given that they may very well run in parallel). Also, the output is typically uploaded when running on CI, etc., and available through a web-interface, instead of trying to parse huge console logs.
