### ISSUE TITLE
An exception occurred while invoking executor...

### ISSUE THREAD

**Issue by jcmrva** [YoloDev/YoloDev.Expecto.TestSdk#15]
> An exception occurred while invoking executor 'executor://yolodev/expecto': Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean, Boolean)'.

The latest Expecto [added a flag](https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L876), changing the signature.

Quick repro using the template
`dotnet new expecto -lang F#`
`dotnet test`

A return of issue #3

Workarounds:

1. `dotnet run` the test project
2. Pin Expecto to an older version (8.3.0)

I believe this just needs a rebuild.

For a longer term solution, I'd hoping this will restart the discussion about improving change resilience between Expecto and its test adapters.  

https://github.com/haf/expecto/issues/211#issuecomment-358627822
https://github.com/haf/expecto/issues/204

**Comment by Alxandr** [comment]
Expecto version is set to 7.0.0 though? That being said, the fact that `8.4.0` is a breaking change is bad SemVer.

**Comment by Alxandr** [comment]
Yeah. The issue here is that the template uses version `*` for expecto I think. Which works fine as long as expecto doesn't have breaking changes. What I should probably do is set a range version for this library to be (in this case) `(7.0.0,8.0.0]` or something like that. And then do a update that moves it to `(8.0.0,9.0.0]`. This will not help when expecto is doing breaking changes without updating the major version number though.

**Comment by Alxandr** [comment]
@ AnthonyLloyd any chance expecto can try to stick to semver compliant updates?

**Comment by Alxandr** [comment]
Sure, but as it stands, config changes are breaking changes in the public api, regardless of your preference. It breaks binary compatibility. That's just how F#/.NET works.

**Comment by Alxandr** [comment]
Actually, (and I don't know if this has been suggested), but you could solve the issue by making the config opaque, and provide accessors for it.

```fsharp
let myConfig =
  defaultConfig
  |> withNoSpinner true

let noSpinner = isNoSpinner myConfig
```

Lenses could also be provided. You could even make the config into a `Conf -> Conf` function, so you didn't need to have `defaultConfig` public at all.

**Comment by AnthonyLloyd** [comment]
Technically maybe. Many fake APIs use a record. They should be a DU and I think are moving that way. In reality people don't construct the record from scratch. I think for the next major release I will look to convert to a DU.

**Comment by Alxandr** [comment]
Btw; I'm not either constructing from scratch. `with` expressions breaks when you add options.

**Comment by AnthonyLloyd** [comment]
Sure, but not for users, just SDKs that compile with different versions.

**Comment by MarneeDear** [comment]
I am getting this error, now, too, with the latest Expecto version that just came out -- 8.10+

You can see my report here:
I get this error when I `dotnet test` on a new Expecto project:

> Starting test execution, please wait...
An exception occurred while invoking executor 'executor://yolodev/expecto': Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean, Boolean, Boolean)'.

Steps:

## Create a new expecto project

`dotnet new expecto`

## Build the project

`dotnet build`

Build runs, does a restore, there are no errors.

## Run the tests.

`dotnet test`

## Get this error:

> Starting test execution, please wait...
An exception occurred while invoking executor 'executor://yolodev/expecto': Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean, Boolean, Boolean)'.

My `dotnet --info`

```text
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

I also reported this on the template project:
https://github.com/MNie/Expecto.Template/issues/14

**Comment by MarneeDear** [comment]
I had to go back to version `8.9.1` to get the tests to run. In the fsproj from the expecto template the Expecto version is set to this:

`<PackageReference Include="Expecto" Version="8.*" />`

Maybe versions 8.10+ are not compatible with the `Yolo` test runner specified in the template's `fsproj`.

`<PackageReference Include="YoloDev.Expecto.TestSdk" Version="0.*" />`

**Comment by AnthonyLloyd** [comment]
To make this more compatible in future Expecto has switched to a CLIArguments DU instead of a config record. The TestSdk should move to using this.

**Comment by Alxandr** [comment]
I'll take a look at it later today if I have time. If not, I can't guarantee anything till next week as I have family visiting this week.

**Comment by Alxandr** [comment]
@MarneeDear can you test if `0.7.1-expecto-config-du.12+5df52da` solves your problem? It's abailable from myget https://www.myget.org/gallery/yolodev (link is likely to be broken about 15 minutes as it was just updated).

**Comment by MarneeDear** [comment]
Thank you. I would be glad to test.

Should I be able to see it online? I don't see it in the gallery. I configured NuGet to use your gallery but `dotnet restore` doesn't find the package.

This is what I see:

```
C:\Users\marnee\Dropbox\expecto-broken\test\test.fsproj : error NU1102:   - Found 26 version(s) in Yolo [ Nearest version: 0.7.0 ]
```

**Comment by Alxandr** [comment]
You're right. My bad. Published now: https://www.myget.org/feed/yolodev/package/nuget/YoloDev.Expecto.TestSdk/0.7.1-expecto-config-du.13+f519586

**Comment by Alxandr** [comment]
0.8.0 released 🎉
