### ISSUE TITLE
'executor://yolodev/expecto': Not implemented

### ISSUE THREAD

**Issue by trbarrett** [YoloDev/YoloDev.Expecto.TestSdk#16]
Hi, I'm having some issues running my expecto tests using this library.

The tests are discovered and appear in the test explorer, but whenever I select and run a test I get this executor error:

```
[16/10/2018 1:39:54 PM Informational] ------ Run test started ------
[16/10/2018 1:39:59 PM Error] An exception occurred while invoking executor 'executor://yolodev/expecto': Not implemented (run testcases)
[16/10/2018 1:40:00 PM Informational] ========== Run test finished: 0 run (0:00:05.6159986) ==========
```

I'm running
- Visual Studio 2017: 15.8.3
- YoloDev.Expecto.TestSdk: 0.5.0
- .Net Core: 2.1
- F# Core: 4.5.2
- Expecto: 8.4.2

FYI: I did have to change the test projects from executable to library for the tests to be discovered.

**Comment by Alxandr** [comment]
Yes. There are parts of the functionality of being a test runner that has not been implemented (I didn't need them myself). I doubt I'll have the time to look at this within a week, but if you would like to drop a PR I'd gladly do the review. If not I'll try to get to it as soon as I can.

**Comment by Alxandr** [comment]
I've created a PR that should, in theory, solve this. But I don't know how to test it. I don't currently have access to a windows machine, and I would also really like to be able to automate these tests somehow.
