### ISSUE TITLE
Setting Expecto's settings record

### ISSUE THREAD

**Issue by TheAngryByrd** [YoloDev/YoloDev.Expecto.TestSdk#20]
How would someone go about settings to [ExpectoSettings](https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L844) when using this with `dotnet test`?

This [ExpectoConfig](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/e57b2577119725f4d86d63567db59f231e6ca89b/src/YoloDev.Expecto.TestSdk/execution.fs#L133) doesn't seem like it's able to set anything.

**Comment by Alxandr** [comment]
You can pass in something called run settings using an XML file. Though I don't think it's ever been tested cause I never needed it myself, so I'm not sure how you pass it in. The available settings to override can be seen here: https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/src/YoloDev.Expecto.TestSdk/settings.fs#L6

This should be pretty easy to extend to other expecto config settings if needed.

**Comment by TheAngryByrd** [comment]
I'll take a look today. If I get anywhere I'll submit a PR with docs. Thanks!

**Comment by Alxandr** [comment]
Docs PRs would definitely be appreciated 👍

**Comment by Alxandr** [comment]
@TheAngryByrd Did you manage to get it working? Or do you need more settings settable?

**Comment by TheAngryByrd** [comment]
Life has a way of getting in the way 😞 .  I might get time this weekend.

**Comment by TheAngryByrd** [comment]
Ok, so I took a look during lunch.

So it looks like we can pass arguments via the CLI: 

```
$ dotnet test --help 

[removed for brevity]

RunSettings arguments:
  Arguments to pass as RunSettings configurations. Arguments are specified as '[name]=[value]' pairs after "-- " (note the space after --).
  Use a space to separate multiple '[name]=[value]' pairs.
  See https://aka.ms/vstest-runsettings-arguments for more information on RunSettings arguments.
  Example: dotnet test -- MSTest.DeploymentEnabled=false MSTest.MapInconclusiveToFailed=True
```

So yeah it looks like we can pass along settings, but we'll have to basically set Expecto settings.

My thoughts would be do something like prepend `Expecto.` to namespace the keys, keeping yolodev's testsdk separat.  Then the parser can set an [expecto config](https://github.com/haf/expecto#the-config) on the RunSettings

`dotnet test -- TargetFrameworkVersion=netcoreapp2.1 Expecto.parallel=true Expecto. failOnFocusedTests=true`

We might want to consider allowing people to pass case insensitive arguments too as I noticed the [XML parsing code](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/src/YoloDev.Expecto.TestSdk/settings.fs#L56) is looking for the PascalCase, but if someone was looking at the settings record it's in camelCase.

**Comment by TheAngryByrd** [comment]
Hmm I was considering reusing Expecto's cli fold code to avoid duplication but it's private.

https://github.com/haf/expecto/blob/dd1f486183cc5f2198b016b04285f5be7cfc8866/Expecto/Expecto.fs#L1814

Think it's worth opening an issue over there? That would require the latest this to be on the latest expecto though, which I'm not sure on your thoughts about bumping the minimum.

**Comment by Alxandr** [comment]
I don't mind keeping this package targeting latest Expecto, and feature parity would definitely be nice.

**Comment by slang25** [comment]
Thanks for the excellent work all 😄
