### ISSUE TITLE
Set GenerateProgramFile to False by default

### ISSUE THREAD

**Issue by inosik** [YoloDev/YoloDev.Expecto.TestSdk#24]
I wonder if this package should set the `GenerateProgramFile` property to `False` by default. Users have to do this themselves at the moment if the project is a console application.

We can also make it conditional and only set the value to `False` if the `OutputType` is set to `Exe` or `WinExe`.

**Comment by Alxandr** [comment]
Last I checked you need the program file (or rather, you need a main method), else the F# compiler messes up module values. The ability for the compiler/tooling to generate the program file itself was added to address this (previously, you had to manually add an entry-point to any F# test library).

You can read some more about it here: https://github.com/dotnet/netcorecli-fsc/issues/79

The discussion was happening all over the place when this was going on, and I remember @dsyme commenting on *why* this works as it does, but I don't remember where that happened. But I do believe if you disable the program file, you will start seeing weird test failures.

**Comment by inosik** [comment]
Looks like the the issue you linked applies to class libraries, right? In my case, I already have a `Program.fs` to simply <kbd>F5</kbd> while developing.

FYI, the `xunit` project template sets `GenerateProgramFile` to `False` as well. It already includes a dummy `Program.fs`.

**Comment by Alxandr** [comment]
Test projects tend to be class libraries though. And as you saw in the project I linked, xunit had problems with people just deleting the `Program.fs` (I used to be one of those people).

**Comment by inosik** [comment]
> Test projects tend to be class libraries though.

That's true for xUnit and NUnit, but also Expecto?

What if we added something like this to the `.props` file of this package:

``` xml
<GenerateProgramFile Condition="$(OutputType) = 'Exe'">False</GenerateProgramFile>
```

Then class libraries will still get a generated `Program.fs`.

**Comment by Alxandr** [comment]
Problem is, that if I'm not wrong, the test-sdk will set the `OutputType` to `Exe` for you, automatically, in test projects. At least it used to. IIRC this was sort of the crux of the matter.

.NET Core test runner required exe projects.
F# did bad things when you had exe projects with no entrypoint.

**Comment by inosik** [comment]
> the test-sdk will set the OutputType to Exe for you

You're right, _Microsoft.NET.Test.Sdk_ does that indeed. Manually setting that property it is then.
