### ISSUE TITLE
Colored output makes error text unreadable 

### ISSUE THREAD

**Issue by Lanayx** [YoloDev/YoloDev.Expecto.TestSdk#25]
The issue can be seen in both Test Explorer and `dotnet test` command's output
The details can be found in those comments
https://github.com/haf/expecto/issues/331#issuecomment-508266009
https://github.com/haf/expecto/issues/331#issuecomment-508849054

**Comment by Alxandr** [comment]
This should be reasonably easy to add support for. It just needs to be added to the settings parser: https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/src/YoloDev.Expecto.TestSdk/settings.fs#L124

**Comment by MaxWilson** [comment]
It should also be set to colours 0 by default, right, so that non-garbled output will show up in VS automatically? I submitted a PR with that assumption.
