### ISSUE TITLE
Support for Expecto 0.9

### ISSUE THREAD

**Issue by Swoorup** [YoloDev/YoloDev.Expecto.TestSdk#29]
Current version of YoloDev appears to restrict expecto to >= 8.10 < 9.0

Any issues with 9.0 currently?

**Comment by Swoorup** [comment]
https://github.com/haf/expecto/issues/381#issuecomment-613897068

**Comment by cmeeren** [comment]
I'd very much like to see 9.0 support, too. Hopefully it's just a metadata update and release; there's been a few breaking changes in 9.0, but AFAIK not too many/severe. So perhaps YoloDev isn't affected by them.

**Comment by Swoorup** [comment]
Appears to working with the latest release. Thank you @MNie

**Comment by xperiandri** [comment]
Same issue now for Expecto 10.0

**Comment by Alxandr** [comment]
There is already an open PR for that: https://github.com/YoloDev/YoloDev.Expecto.TestSdk/pull/120.
