### ISSUE TITLE
Getting error executing tests

### ISSUE THREAD

**Issue by rodrigovidal** [YoloDev/YoloDev.Expecto.TestSdk#3]
Hi @Alxandr,

I'm running into this error with "dotnet test"
using the following package versions

```xml
<PackageReference Include="Expecto" Version="5.*" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
<PackageReference Include="YoloDev.Expecto.TestSdk" Version="0.2.0" />
```

Starting test execution, please wait...
An exception occurred while invoking executor 'executor://yolodev/expecto': Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean)'.

Is it a known issue?

**Comment by Alxandr** [comment]
No. Might be a breaking change somewhere.

**Comment by MNie** [comment]
@Alxandr I suppose it's related to [this](https://github.com/haf/expecto/issues/211) change in expecto.

**Comment by Alxandr** [comment]
Modifying public records is a breaking change: https://github.com/haf/expecto/commit/d145a43ad753bc48ef5b3e3f34130966a210a0ab#diff-312b950ecb6e71200586b2408ab6e821R838

**Comment by whitebear-gh** [comment]
I have the same issue exactly the same issue after upgrading from `5.0.1` to `5.1.2` 
```An exception occurred while invoking executor 'executor://yolodev/expecto': Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean)'.```

**Comment by Alxandr** [comment]
Yeah, it's a breaking change in expecto. I need to release a new version of the test sdk.

**Comment by Alxandr** [comment]
`v0.3.0` is being published. Templates should probably be updated, but I don't remember who owns them/where they exist.

**Comment by rodrigovidal** [comment]
Thanks @Alxandr
