### ISSUE TITLE
Why does this depend on FSharp.Core?

### ISSUE THREAD

**Issue by jamesottaway** [YoloDev/YoloDev.Expecto.TestSdk#31]
The latest version has a hard dependency on FSharp.Core v4.7.1, where I think the default that ships with the latest version of .NET Core is 4.7.0, meaning without bumping my application up to match I cannot install YoloDev.Expecto.TestSdk

I was originally going to ask why this library has a dependency on such a new version of FSharp.Core, especially given [advice like this](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html), but now I'm wondering why it even depends on it at all?

I see that Expecto depends on FSharp.Core, so surely it's sufficient to rely on the transient dependency. Right?

Either it should be lowered or removed, as the version in the current dependency is too restrictive.

**Comment by Alxandr** [comment]
Not sure. I've had a ton of issues with FSharp.Core as a nugget package in the past, so it got added at some point. Also, from the page you linked there are examples like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
    <PackageReference Update="FSharp.Core" Version="4.2.3" />
  </ItemGroup>
</Project>
```

In other words, it's not even internally consistent with its own advice. I'm not opposed to changing this though, but as far as I've seen, it's common to have a dependency on *some* FSharp.Core version in libraries. If not, they might not work after all.

**Comment by Alxandr** [comment]
And with regards to your point on transitive dependencies, that would mean that if Expecto removes its dependency no `FSharp.Core` (I doubt this is possible, but let's just imagine it was) that would be a breaking change, cause now my library suddenly might not work anymore.

**Comment by MNie** [comment]
@Alxandr if we could downgrade the FSharp.Core to the 4.7.0 (default for .net core 3.1) I would be happy, then I could remove [this](https://github.com/MNie/Expecto.Template/blob/4f97834969dde7336318d134667d36bb4c109993/ExpectoTemplate.fsproj#L18) little bastard from a template :)

**Comment by Alxandr** [comment]
It seems to me from the page posted above that [this](https://www.nuget.org/packages/FSharp.Core/4.3.3) might be the version we should use rather?

**Comment by jamesottaway** [comment]
That article is quite old, so the specific versions mentioned might not be right. For my purposes, v4.7.0 would work, but don't let me stop you going back earlier. The advice in that article to [target as low a version as possible for a library](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-should-target-lower-versions-of-fsharpcore) is what I like.

**Comment by MNie** [comment]
> That article is quite old, so the specific versions mentioned might not be right. For my purposes, v4.7.0 would work, but don't let me stop you going back earlier. The advice in that article to [target as low a version as possible for a library](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-should-target-lower-versions-of-fsharpcore) is what I like.
> 
> In case it helps, this is the error I got on `dotnet restore` that prompted me to open this issue:
> 
> ```
> /var/lib/buildkite-agent/builds/ip-172-31-1-104-ap-southeast-2-compute-internal-7/stacktrace/urgent-care-server/urgent-care/server/tests/Application/Application.Tests.fsproj : error NU1605: Detected package downgrade: FSharp.Core from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.
> /var/lib/buildkite-agent/builds/ip-172-31-1-104-ap-southeast-2-compute-internal-7/stacktrace/urgent-care-server/urgent-care/server/tests/Application/Application.Tests.fsproj : error NU1605:  Application.Tests -> YoloDev.Expecto.TestSdk 0.9.1 -> FSharp.Core (>= 4.7.1) 
> /var/lib/buildkite-agent/builds/ip-172-31-1-104-ap-southeast-2-compute-internal-7/stacktrace/urgent-care-server/urgent-care/server/tests/Application/Application.Tests.fsproj : error NU1605:  Application.Tests -> FSharp.Core (>= 4.7.0)
> ```
> 
> I also noticed that, unless the NuGet stats are off, there haven't been any downloads of v0.9.1, which may be related to the dependency version range being so restrictive.

I wouldn't relay on what nuget.org is showing In terms of a number of downloads since I download 0.9.1 a couple of times. Also Expecto.Template is using the testsdk 0.9.1. The hint there was to add the following line to `.fsproj`

```xml
    <PackageReference Update="FSharp.Core" Version="4.*" />
```

Maybe going to the lowest possible would be feasible, but I think 4.7.0 would be a way to go. Also based on the following:
Expecto -> 4.6.0
![image](https://user-images.githubusercontent.com/7689103/80221005-f4222d00-8644-11ea-9145-a5189c438419.png)

.net core 3.1 -> 4.7.0
The lowest possible version we should use is 4.6.0.

**Comment by Alxandr** [comment]
4.6.0 sounds reasonable then, given expecto is a dependency.

**Comment by Alxandr** [comment]
That last commit took my CI from being semi-broken to being dead-as-a-fish-broken. Anyone mind trying to build locally to see if they have errors (here it builds just fine). CI gives no useful output :-/

**Comment by MNie** [comment]
@Alxandr I think that `packages.props` is not visible inside of certain projects. When I build via `dotnet build` the whole solution, everything is okay, but when I go inside the `test/Sample.Test` project and try to `dotnet build & dotnet run` I get the following error:

![image](https://user-images.githubusercontent.com/7689103/80274107-55471080-86d8-11ea-8b6c-ecba3aba3c6e.png)

This indicates that the restore fails because we don't have information about referenced packages.

Also because of `Microsoft.Build.CentralPackageVersions` in `*.fsproj` files the solution is not loading at all in Jetbrains.Rider.

**Comment by Alxandr** [comment]
I'd rather have central package version than rider support TBH, but the weird thing is how this works perfectly on my machine and fails with no output at all on CI. And apparently on your machine.

![image](https://user-images.githubusercontent.com/112334/80277075-d5777100-86ec-11ea-80cc-9fe9007b6a89.png)

Btw, why are you doing dotnet run on a test project anyways?

**Comment by Alxandr** [comment]
Derp. Was just caused by a gitignore on global.json. If you want to, you can check if rider works too now.

**Comment by Alxandr** [comment]
0.9.2 is pushed 🎉
