### ISSUE TITLE
argument handling

### ISSUE THREAD

**Issue by vilinski** [YoloDev/YoloDev.Expecto.TestSdk#37]
There is a difference how the cli arguments are handled:

This doesn't run the tests if there are focused, which is correct

```shell
$ dotnet run --fail-on-focused-tests
$ dotnet run -- --fail-on-focused-tests
[11:59:34 ERR] It was requested that no focused tests exist, but 2 focused tests were found. <Expecto>
```

This complains about unknown arguments, which can be right

```
dotnet test --fail-on-focused-tests
```

But I didn't expect following command just ignores this arg and runs focused tests instead of failing:

```
dotnet test -- --fail-on-focused-tests
```

Is it intentional behavior or is it a bug?

**Comment by Alxandr** [comment]
`dotnet test` arguments are not passed to expecto, but to the .NET test runner (mstest I believe). So there is no way we can control how it handles argument (nor should there be). If you want to pass fail on focused tests, the way to do that is something like this: `dotnet test -- Expecto.fail-on-focused-tests=true`. See repo [readme](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/README.md#configuration) for more info.
