### ISSUE TITLE
Rework gitversion logic

### ISSUE THREAD

**Issue by gdziadkiewicz** [YoloDev/YoloDev.Expecto.TestSdk#40]
A workaround that ignores the error and accepts potentially invalid commit-count has been done as part of #39 

The output from the `Output version` step of the CI build, which runs the script in verbose mode making the problem visible:

> Run bash ./script/git-version.sh --verbose get
>   bash ./script/git-version.sh --verbose get
>   shell: /bin/bash -e {0}
>   env:
>     DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
>     DOTNET_CLI_TELEMETRY_OPTOUT: 1
>     DOTNET_ROOT: /home/runner/.dotnet
> git-version: Calling: get-version 
> git-version: Calling: get-exact-version-tag 
> git-version: Calling: get-prev-version-tag 
> git-version: last-version-tag=v0.10.1
> git-version: Calling: get-next-full-version v0.10.1
> git-version: next-full-version=0.10.2
> git-version: Calling: get-branch-version-meta v0.10.1
> git-version: Calling: get-branch-name 
> git-version: branch-name=HEAD
> git-version: Calling: get-branch-short-name HEAD
> git-version: did not match
> git-version: short-name=HEAD
> _**git-version: Calling: get-branch-point HEAD master
> fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'**_
> git-version: branch-point=
> git-version: Calling: get-commit-count 
> git-version: commit-count=79
> git-version: short-hash=6287187
> git-version: branch-meta=-HEAD.79+6287187
> 0.10.2-HEAD.79+6287187

before applying the workaround the part in **bold** ended up in the version string making it invalid.

**Comment by Alxandr** [comment]
I've made a temporary fix so that we can get new versions out. It's temporary (I don't like the solution), but for now it works at least.

**Comment by Alxandr** [comment]
Release pipeline has been updated and no longer uses gitversion at all.
