### ISSUE TITLE
A dot in the test description causes the introduction of a new sub-test(list)

### ISSUE THREAD

**Issue by NicoleRauch** [YoloDev/YoloDev.Expecto.TestSdk#41]
Sometimes I have a dot (i.e. ".") in my test description (usually because I'm using an abbreviation). This causes a sub-test or sub-testlist to be introduced when I look at the tests with .NET Test Explorer in Visual Studio Code.

E.g. the test
```
test "A . B . C" { Expecto.Expect.equal 1 1 "" }
```
is displayed as

<img width="104" alt="image" src="https://user-images.githubusercontent.com/436499/97596545-1d14e780-1a05-11eb-9191-cf44ce1f6b5c.png">

instead of as a single test with the label "A . B . C".

I've never seen this behavior in Expecto itself therefore I suspect it is caused by YoloDev?

**Comment by Alxandr** [comment]
It first needs to be figured out whether or not this is caused by expecto, yolodev.expecto, or just plain old VS test explorer (my guess). Try making a xunit test project with a test name with `.` in it (I *think* this is doable in F#), does it have the same effect?

**Comment by NicoleRauch** [comment]
Thanks for getting back to me! Meanwhile I've discovered the old issue #26 from which I believe this to be a feature instead of a bug 😂 So I'm closing this issue.

In case anybody is interested in the details: It seems to be configurable in Expecto whether . or / is used? (I did not try because I've already removed the dots from my test labels.)
