### ISSUE TITLE
Restore .NET Framework compatibility

### ISSUE THREAD

**Issue by cmeeren** [YoloDev/YoloDev.Expecto.TestSdk#44]
YoloDev.Expecto.TestSdk 0.8.0 was compatible with `net461`. But 0.9.0 and 0.9.1 only target `netcoreapp2.0`. This makes it impossible to run tests for .NET Framework.

I see there has been some PRs back-and-forth regarding targeting `net461`. It seems that the attempt failed. But perhaps `net472` can be supported? It has full support for `netstandard2.0`.

**Comment by Alxandr** [comment]
Now that net5 has launched, I'm not interested in investing time in supporting framework anymore.

**Comment by cmeeren** [comment]
Fair enough, but did it actually cause any added complexity other than having `net4xx` in the `TargetFrameworks` in the project file? Often that's all that's needed (though not always, and if that's not the case here, I understand your position).

**Comment by Alxandr** [comment]
It's not. Test adapters requires to be found by the test runner. They are not build time dependencies, but "test time", and it's tricky to get working and hard to debug why when it's not.

**Comment by Alxandr** [comment]
That being said, if you can get it working, without making a horrible mess of the build, I'm open to reviewing and accepting a PR .

**Comment by cmeeren** [comment]
Thanks for the clarification. I'll see if I can get around to experimenting some time, but it's not something I'll start on right away.
