### ISSUE TITLE
Changelog for all the releases (including 1.0.0) a week ago?

### ISSUE THREAD

**Issue by cmeeren** [YoloDev/YoloDev.Expecto.TestSdk#91]
7 days ago there was suddenly released quite a few versions all at once:

![image](https://user-images.githubusercontent.com/7766733/158134372-db2bac74-270d-443f-9d2b-620946d76398.png)

Was this intended, or has something automatic failed? And is there a changelog for the changes between 0.12.13 and 1.0.0?

**Comment by cmeeren** [comment]
This seems to be an error.

In [this release build](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/runs/5450033791?check_suite_focus=true), the GH tag matches the assembly version: 0.12.20

However, in [the subsequent release build](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/actions/runs/1946576560), there are many warnings about a missing `version.txt` file, and it seems it defaults to `1.0.0`, which was published.

I suggest unlisting 1.0.0 on NuGet and elsewhere (and of course, fixing the build pipeline).

**Comment by cmeeren** [comment]
Additionally, I suggest going through the other releases from 0.12.13 to 0.12.20 and making sure the publishing of all of them was intended (or, at the very least, that 0.12.20 is OK to be used as it currently exists on NuGet).

**Comment by Alxandr** [comment]
You're right. 1.0.0 is wrong and should not have been published. Or rather, it should be, but not as 1.0.0.

**Comment by Alxandr** [comment]
As may be apparent, I'm not very active on this repository - but the issue with deployments should in theory be fixed now (still monitoring the situation). A new 0.13.0 should be available on nuget within the hour as long as everything works as expected.
